### PR TITLE
Use the Edge Diagnostics Adapter

### LINKED ISSUE #14: Use the Edge Diagnostics Adapter
Microsoft just released the [Edge Diagnostics Adapter](https://github.com/Microsoft/edge-diagnostics-adapter) for debugging Edge. Since it's tricky to launch Edge as a modern-style app (and there are still bugs on master currently), I'm going to try switching to this adapter.

If this is fixed, not much else will block this launcher from being published.

### PR DESCRIPTION
**Pull request by nickserv**
WIP

When this is done, this launcher should be in a working state and ready to be published.

Fixes #14.

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@nicolasmccurdy, I can get Microsoft people to help out if need be (I know folks on the Edge team and I'm sure they would be happy to help), but can you get all this stuff rebased, etc. so we can show it to them.

**Comment by nickserv** [comment]
Thanks for the support, @marcoscaceres! This diff is a little messy because I pulled in some upstream changes (on karma-ie-launcher) without updating my master branch, but I'll probably clean this up for code review when I get closer to having this working.

**Comment by marcoscaceres** [comment]
Ok, np. I'm here to help! Feel free to assign me reviews or whatever. If you get stuck with anything, I am always happy to bounce ideas off or find the right people.

**Comment by nickserv** [comment]
Thanks again. Please let me know if you have any thoughts on this comment: https://github.com/nicolasmccurdy/karma-edge-launcher/issues/14#issuecomment-216283920

**Comment by marcoscaceres** [comment]
Watching #14 with great interest! Great to see the Microsoft folks in there!!!! ❤️

**Comment by nickserv** [comment]
Replaced with #19. I'm using [edge-launcher](https://github.com/MicrosoftEdge/edge-launcher) instead.

**Pull request closed without merging**
