### PR TITLE
Terminate MS Edge via taskkill

### PR DESCRIPTION
**Pull request by harimambura**
Temporary fix problem, that MS Edge doesn't close

### CODE REVIEW

**Comment by nickserv** [comment]
Thanks for your contribution! It seems to work on my minimal example project but I'm going to test it with a larger project to make sure it doesn't affect any other launchers.

In the meantime, I've noticed that GitHub isn't recognizing that your commits are coming from your account. Would you like to fix this so you'll show up in the contributors graph? If you don't know how, I can rebase this for you if you give me your git name and account email.

```
Unrecognized author. If this is you, make sure zhiryakov@scand.com is associated with your account. Click to add email addresses in your account settings.
```

**Comment by harimambura** [comment]
Thanks for your answer!
I tried to launch tests with this changes in parallel with IE, Chrome and FF launchers and all works correctly.

Sorry, this is my working email, my personal email is harimambura@gmail.com and harimambura is git name. I wonder if you could rebase this commits. Thanks in advance!

**Comment by nickserv** [comment]
I squashed your commits into one (since the others were minor code style changes) and changed the author. I'll take another look at testing this soon.

**Comment by harimambura** [comment]
Thank you so much

**Comment by nickserv** [comment]
I managed to make this async and fix the Karma warnings. 😄 This should be ready, just going to do some extra testing first.

**Comment by unkiwii** [comment]
This works, Edge is killed, but the next time it starts just opens all the previous tabs, even configured to not open those tabs.

If I close Edge normally (X button or Alt+F4) the tabs are closed.

So after 10 test runs completed (passed or failed), the 11th time I run tests Edge opens 10 "Karma" tabs.

This is not scalable in an automated setup.

I found that running `taskkill` twice without` /f `parameter actually kills Edge but in a normal way.

I will fork this and made a pull request

**Pull request merged**
