### PR TITLE
Use MicrosoftEdgeLauncher to launch Edge with keepalive

### PR DESCRIPTION
**Pull request by nickserv**
The [MicrosoftEdgeLauncher](https://github.com/MicrosoftEdge/MicrosoftEdgeLauncher) project includes an EXE for launching Edge with a keepalive flag (`-k`). I decided to switch development to relying on this project because without the keepalive flag, spawning Edge through `start` would cause Karma to think that the browser crashed prematurely (but it was just the launcher process closing when Edge was launched). While I'm not 100% sure that my code is stable enough to be ready, this seems to be working a lot more consistently than my previous attempts.

### CODE REVIEW

**Comment by nickserv** [comment]
Hi @andysterland, this is using your work on the [keepalive flag](https://github.com/MicrosoftEdge/MicrosoftEdgeLauncher/pull/16).  Would you mind taking a look? Also thanks for this, it's the simplest way so far that I've been able to keep the launching process running with the Edge session so that Karma doesn't think it crashed.

Right now I'm just calling Microsoft Edge Launcher with the unmodified URL and the `-k` flag. I have the latest launcher EXE committed to this project temporarily. Do you have any thoughts on a better way to depend on that project? I was thinking about using a runtime HTTP request or an npm install hook (probably better) to download the latest binary off GitHub.

**Comment by andysterland** [comment]
Packaging up in NPM would be a good option as most of the things that depend on it will be using NPM.  Does that work for you?

**Comment by nickserv** [comment]
That would definitely be useful for this project (assuming you mean packaging the EXE into an npm package). Let me know if there's anything I could contribute to that.

**Comment by nickserv** [comment]
@andysterland Thank you for the npm package, it makes things much simpler.

I think this pull request might be complete, but I'm going to wait to merge until I get more testing done.

**Comment by nickserv** [comment]
I made an [example project](https://gist.github.com/nickmccurdy/a256f0556ea20e77e5650e041acf1ade) and this seems to be working smoothly.

**Pull request merged**
